# Generated by Django 5.1.4 on 2025-02-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_article',
            name='stock_article',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
