# Generated by Django 5.1.4 on 2025-02-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_stock_article_stock_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventes',
            name='article_nom',
        ),
    ]
