# Generated by Django 5.1.4 on 2025-02-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_ventes_article_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventes',
            name='prix',
            field=models.FloatField(editable=False),
        ),
    ]
