# Generated by Django 5.1.4 on 2025-02-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_ventes_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventes',
            old_name='quantite',
            new_name='quantite_achetee',
        ),
    ]
