# Generated by Django 5.1.4 on 2025-02-14 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_utilisateur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock_article',
        ),
    ]
