# Generated by Django 5.1.4 on 2025-02-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_delete_stock_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='id_facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='article',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.article'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ventes'),
        ),
    ]
