# Generated by Django 5.1.4 on 2025-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_facture_id_facture_facture_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='id_ventes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom_categorie',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
