# Generated by Django 5.1.4 on 2025-02-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_facture_client_facture_id_ventes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='id_article',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='id_ventes',
        ),
        migrations.AddField(
            model_name='facture',
            name='nom_article',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ventes'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.article'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_vente',
            field=models.IntegerField(null=True),
        ),
    ]
