# Generated by Django 5.1.4 on 2025-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_facture_id_article_remove_facture_id_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventes',
            name='article_nom',
            field=models.CharField(null=True),
        ),
    ]
