# Generated by Django 5.1.4 on 2025-02-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_ventes_article_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='id_vente',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='nom_client',
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
