# Generated by Django 5.1.4 on 2025-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_facture_id_vente_remove_facture_nom_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='prix',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='nom_article',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
