# Generated by Django 5.1.4 on 2025-02-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_facture_prix_alter_facture_nom_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='vente',
        ),
        migrations.AddField(
            model_name='facture',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
