# Generated by Django 5.1.4 on 2025-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_facture_vente_facture_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='prix',
            field=models.FloatField(null=True),
        ),
    ]
