# Generated by Django 5.1.4 on 2025-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_facture_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='prix',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='facture',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
