# Generated by Django 5.1.4 on 2025-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_facture_prix_alter_facture_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='prix',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
