# Generated by Django 5.1.4 on 2025-02-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_facture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventes',
            name='payement',
            field=models.IntegerField(choices=[(0, 'Mixx  By Yas'), (1, 'Moov Money')], default=0),
        ),
    ]
