# Generated by Django 5.1.4 on 2025-02-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_ventes_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventes',
            name='payement',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('TMONEY', 'Tmoney'), ('FLOOZ', 'Flooz')], default='CASH', max_length=100),
        ),
    ]
