# Generated by Django 5.1.4 on 2025-02-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_ventes_payement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventes',
            name='article_nom',
        ),
    ]
