# Generated by Django 5.1.4 on 2025-02-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_ventes_article_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='vente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ventes'),
        ),
        migrations.AddField(
            model_name='ventes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='ventes',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.article'),
        ),
    ]
