# Generated by Django 5.1.4 on 2025-02-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_facture_vente_ventes_client_alter_facture_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.article'),
        ),
    ]
