# Generated by Django 5.1.4 on 2025-02-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_facture_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventes',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.client'),
        ),
    ]
